### List all
GET {{host}}/api/v1/shopping_lists
Accept: application/json
Authorization: Bearer {{token}}

### Show item
GET {{host}}/api/v1/shopping_lists/1
Accept: application/json
Authorization: Bearer {{token}}

### Add item
POST {{host}}/api/v1/shopping_lists
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Test 1"
}
